### ISSUE TITLE
Upgrade this project to kamon 0.5.0 with akka cluster

### ISSUE THREAD

**Issue by JosephKiranBabu** [muuki88/activator-akka-kamon#1]
It would be useful if this project is available on the latest version of kamon which is said to have support for akka cluster. Trying out this activator template with kamon 0.3.4 gives issues when trying to use it with a multi-node akka cluster.

**Comment by muuki88** [comment]
Thanks for reporting. Would you like to make a PR?

**Comment by JosephKiranBabu** [comment]
Kamon 0.5.0 has some issues. The Kamon team is releasing patches. Since this is a template project, it better be a stable version of Kamon. Maybe this is a bad time to upgrade. Still, I will try to make a PR soon as soon as I can get it working with 0.5.1.
